language: java
jdk: 
 - openjdk6
services:
 - redis-server
script: ant -buidlfile build.xml
deploy:
   provider: cloudfoundry
   username: hskramesh@gmail.com
   password: itsmyPivotal
   api: https://api.run.pivotal.io
   organization: hskramesh
   space: development
