language:java
jdk:
	- openjdk8
deploy:
   edge: true
   provider: cloudfoundry
   username: hskramesh@gmail.com
   password: itsmyPivotal
   api: https://api.run.pivotal.io
   organization: hskramesh
   space: development